### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by Hiroya-Happy** [Hiroya-Happy/protospace-33830#1]
https://github.com/Hiroya-Happy/protospace-33830

**Comment by mo1015** [comment]
ご提出ありがとうございます！お待たせいたしました。

確認したところ、提出いただいたURLでprotospaceにアクセスできませんでした。
本番環境で確認ができるprotospaceのURLを再度記載いただくようお願いいたします。

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by Hiroya-Happy** [comment]
https://protospace-33830.herokuapp.com/

**Comment by mo1015** [comment]
再提出ありがとうございます！
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [ ] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移するようにしましょう**
コメントのユーザー名をクリックしたときに遷移しません。（トップページに遷移してしまいます）

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by Hiroya-Happy** [comment]
https://protospace-33830.herokuapp.com/

修正しています。
再度、ご確認の程よろしくお願いいたします。

**Comment by mo1015** [comment]
ご提出ありがとうございます！
動作の確認をしたところ、前回依頼箇所の修正が確認できませんでした。
マージやデプロイ忘れの可能性もございますので、再度本番環境で実装できているか確認をお願いいたします。

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by Hiroya-Happy** [comment]
https://protospace-33830.herokuapp.com/

デプロイが出来ていませんでした。
再度、ご確認の程よろしくお願いします。

**Comment by mo1015** [comment]
ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！LGTMです！　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう！
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください。
